name: Build Munki (Manual)

env:
  APP_SIGNING_IDENTITY: "Developer ID Application: Mac Admins Open Source (T4SK8ZXCXG)"
  INSTALLER_SIGNING_IDENTITY: "Developer ID Installer: Mac Admins Open Source (T4SK8ZXCXG)"
  REVISION: 4e35f56b9c19d3dff3dc1bd85c634cbc1b507938 # hardcoded for now until we figure out how we want to tackle this - v6.2.1
  VERSION: 6.2.1

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-12

    steps:
    - name: Checkout munki repo
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      with:
        fetch-depth: 0
        ref: ${{env.REVISION}}
        repository: munki/munki

    - name: Install Apple Xcode certificates
      uses: apple-actions/import-codesign-certs@8f3fb608891dd2244cdab3d69cd68c0d37a7fe93 # v2.0.0
      with:
        keychain-password: ${{ github.run_id }}
        p12-file-base64: ${{ secrets.APP_CERTIFICATES_P12_MAOS }}
        p12-password: ${{ secrets.APP_CERTIFICATES_P12_PASSWORD_MAOS }}

    - name: Install Apple Installer certificates
      uses: apple-actions/import-codesign-certs@8f3fb608891dd2244cdab3d69cd68c0d37a7fe93 # v2.0.0
      with:
        create-keychain: false # do not create a new keychain for this value
        keychain-password: ${{ github.run_id }}
        p12-file-base64: ${{ secrets.PKG_CERTIFICATES_P12_MAOS }}
        p12-password: ${{ secrets.PKG_CERTIFICATES_P12_PASSWORD_MAOS }}

    - name: find the path
      run: ls -la ./

    - name: Build munki package
      run: ./code/tools/make_munki_mpkg.sh -p -S "$APP_SIGNING_IDENTITY" -s "$INSTALLER_SIGNING_IDENTITY"
    
    - name: get environment variables
      id: get_env_var
      run: |
         echo -n "MUNKI_VERSION=${$(find . -type f -name "*.pkg" | sed 's/[^\-]*-//')%.*}" >> $GITHUB_ENV

    - name: Generate changelog
      if: ${{ false }} # disable job or now
      id: changelog
      uses: metcalfc/changelog-generator@afdcb9470aebdb2252c0c95a1c130723c9e21f3a # v4.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        reverse: 'true'

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      with:
        name: Munki v${{env.MUNKI_VERSION}}
        tag_name: v${{env.VERSION}}
        draft: true
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
            This is a test for now
        files: ${{github.workspace}}/*.pkg
